/* Notas del presentador · Pitch WebFlix Shark Tank v2
 * Reparto: Erick abre → Tami → Cris → Vale cierra
 * Énfasis: Experimento (Tami), Prototipo (Cris), Aprendizajes/Decisión (Vale)
 */
window.WEBFLIX_NOTES = [
  {
    id: 0,
    n: "01",
    title: "Portada",
    speaker: "Erick",
    role: "Abre el pitch",
    window: "Setup · saludo",
    onScreen: "Hook “Perdemos 1 de cada 3…” · 310M · 42%→29% · tesis Day-7",
    say: [
      "Hola a todos, espero que se encuentren muy bien. Somos el equipo 5, conformado por Cris, Tami, Vale y yo.",
      "El caso que abordamos plantea el problema de una plataforma global de streaming —que como equipo llamamos WebFlix— donde los usuarios que se suscriben por primera vez no logran descubrir contenido relevante en su primera semana.",
      "Entran con ganas de ver algo, y se topan con un catálogo enorme que todavía no sabe qué les gusta. Consumen muy poco, se frustran, y se van antes de vivir lo que nosotros llamamos el “primer momento de valor”.",
    ],
    highlight: [
      "Presentar al equipo en una frase",
      "Pausa tras el hook de cold start",
      "No leer todos los KPIs de portada",
    ],
    avoid: [
      "No prometer recuperar Day-7 hoy",
      "No alargar el saludo",
    ],
  },
  {
    id: 1,
    n: "02",
    title: "Problema",
    speaker: "Erick",
    role: "Problema · 0:00→1:15",
    window: "0:00 → 1:15",
    onScreen: "42%→29% Day-7 · Watch Time / Sesiones / Churn · honestidad del pitch",
    say: [
      "¿A quién afecta esto? A la base completa de usuarios nuevos, dentro de una plataforma con 310 millones de suscriptores y cerca de 360 millones de usuarios activos al mes, contando perfiles familiares.",
      "Y ojo: los perfiles nuevos dentro de un plan familiar también entran en esta categoría, aunque la cuenta ya sea antigua.",
      "¿Por qué importa resolverlo ahora? Porque el Day-7 Retention —la gente que sigue activa al séptimo día— cayó de 42% a 29%. Trece puntos. Un 31% relativo. Y esto no es un problema de catálogo, es un problema de descubrimiento.",
      "El Day-7 es el outcome de negocio que nos importa recuperar. Pero quiero ser honesto con ustedes desde ahora: el experimento que les vamos a mostrar hoy no prueba el Day-7 directamente. Prueba los pasos previos —activación y relevancia en la primera sesión— que creemos que pueden moverlo.",
      "Guárdense esa distinción, porque va a ser importante más adelante en el pitch.",
    ],
    highlight: [
      "310 M / ~360 M MAU = escala, no tamaño de muestra",
      "−13 pp · ≈31% de caída relativa",
      "Declarar honestidad: no probamos Day-7 directo",
    ],
    avoid: [
      "No decir “el algoritmo está roto”",
      "No vender Day-7 como resultado de este test",
    ],
  },
  {
    id: 2,
    n: "03",
    title: "Entendimiento",
    speaker: "Erick",
    role: "Tres fricciones · 1:15→2:15",
    window: "1:15 → 2:15",
    onScreen: "3 fricciones · insight “supuesto a validar” · cadena no virtuosa",
    say: [
      "Entendemos que existen tres fricciones muy concretas.",
      "Primero: los usuarios nuevos tienen que buscar y recorrer demasiadas categorías antes de encontrar algo que les llame la atención. Los títulos, las imágenes, las descripciones, no les dan suficiente información para decidir rápido.",
      "Segundo: el proceso de onboarding actual, donde piden elegir géneros al registrarse, es lento y poco liviano —no está pensado para completarse en segundos, y eso hace que muchos lo abandonen o lo hagan a medias. No es que sobre un paso, es que el paso que ya existe está mal diseñado.",
      "Tercero, y este fue el insight que más nos costó aislar: el motor de recomendaciones no está roto. Simplemente tarda demasiado en aprender los gustos de alguien que recién llega, porque tiene muy pocas señales para trabajar. No es un problema de oferta —hay contenido de sobra— es un problema de velocidad de personalización.",
      "Y aquí hicimos algo importante como equipo: no asumimos que el motor era la causa. Lo tratamos como un supuesto a validar, no como un hecho. Eso cambió todo nuestro enfoque de experimentación.",
    ],
    highlight: [
      "Frase ancla: “el paso que ya existe está mal diseñado”",
      "Motor no roto → velocidad de personalización",
      "Supuesto a validar, no hecho",
    ],
    avoid: [
      "No culpar al catálogo como única causa",
      "No saltar a la solución sin las 3 fricciones",
    ],
  },
  {
    id: 3,
    n: "04",
    title: "Hipótesis",
    speaker: "Tamara",
    role: "Hipótesis · 2:15→3:10",
    window: "2:15 → 3:10",
    onScreen: "Rediseñar, no agregar · 3 elecciones · guardrail <30 s · H·C ★",
    say: [
      "Con ese entendimiento, priorizamos tres hipótesis usando nuestro tablero: una sobre aprovechar patrones de usuarios similares, otra sobre procesar más rápido las señales de sesión cero, y la que decidimos probar primero porque es la más rápida de validar y la de menor riesgo técnico.",
      "Nuestra hipótesis central es esta: creemos que rediseñar —no agregar— esa selección de gustos y géneros del onboarding, dejándola en solo tres elecciones rápidas, le va a dar al sistema señales suficientes para generar recomendaciones relevantes desde la primera sesión.",
      "Ojo con esto: no es un paso nuevo encima del onboarding actual, es el mismo paso hecho liviano. Por eso el tiempo de selección —menos de 30 segundos— no es un lujo, es un guardrail: si toma más que eso, la hipótesis queda refutada ahí mismo, antes de mirar cualquier otra métrica.",
      "Sabremos que funcionó si disminuye el tiempo hasta la primera reproducción, y si aumenta un 15% la tasa de usuarios que consume contenido durante su primera sesión.",
      "Es una apuesta simple, barata de probar, y que no toca el motor de recomendaciones ni el catálogo. Por eso la pusimos primero en la fila.",
    ],
    highlight: [
      "“Rediseñar, no agregar” es la frase ancla",
      "Guardrail <30 s = refutación inmediata",
      "Señalar H·C / onboarding liviano primero",
    ],
    avoid: [
      "No vender H·A / H·B como parte del test de hoy",
      "No tocar motor ni catálogo en el alcance",
    ],
  },
  {
    id: 4,
    n: "05",
    title: "Experimento ⭐",
    speaker: "Tamara",
    role: "Experimento · 3:10→4:50 · ÉNFASIS",
    window: "3:10 → 4:50",
    onScreen: "Control vs Experimental · umbrales · 30–50 · 7 días · 2 semanas",
    say: [
      "Para probarla sin construir nada del motor real, diseñamos un Wizard of Oz longitudinal. El usuario cree que está recibiendo recomendaciones automáticas, pero en esta primera fase las armamos manualmente según perfiles de gustos predefinidos. Así probamos la idea antes de invertir en ingeniería.",
      "¿Cómo lo hicimos? Reclutamos entre 30 y 50 usuarios nuevos, gente que recién crea su perfil por primera vez —incluyendo perfiles nuevos dentro de cuentas familiares.",
      "Les pedimos elegir tres géneros o títulos durante el onboarding rediseñado. Con eso los asignamos a un perfil de preferencia predefinido, y les mostramos una pantalla de inicio curada según esa elección.",
      "En paralelo, un grupo control recibe una portada genérica comparable, sin selección de preferencias —así cualquier diferencia que veamos se la podemos atribuir a la señal, no al azar. Después seguimos la primera sesión de ambos grupos y los acompañamos siete días con analítica y un diario breve.",
      "La duración total fue de dos semanas: reclutamiento, ejecución y análisis. Por participante, el seguimiento fue de siete días desde el onboarding.",
      "¿Y los criterios de éxito? Que al menos el 80% complete la selección en menos de 30 segundos. Que al menos el 65% haga una reproducción válida en su primera sesión. Que el tiempo mediano hasta esa primera reproducción sea menor a tres minutos. Que el Watch Time de la primera sesión suba un 10% frente al grupo control. Que el 75% califique las recomendaciones con nota 4 o 5. Y que la intención de volver durante la semana aumente un 15%.",
      "Si no se cumple esto, o si la selección aumenta el abandono, la hipótesis queda refutada y volvemos al tablero.",
    ],
    highlight: [
      "⭐ Énfasis del bloque de Tami",
      "Control vs “la apuesta” experimental",
      "WoZ = techo de valor, no promesa del motor",
      "Listar umbrales con calma; no correr",
    ],
    avoid: [
      "No hablar de significancia a escala WebFlix",
      "No confundir curación manual con producto final",
    ],
  },
  {
    id: 5,
    n: "06",
    title: "Herramientas",
    speaker: "Cristian",
    role: "IA copiloto · 4:50→5:25",
    window: "4:50 → 5:25",
    onScreen: "Figma AI · Claude + ChatGPT · ejemplo que cambió el rumbo",
    say: [
      "Con la hipótesis de Tami ya definida, les cuento cómo llegamos ahí.",
      "Usamos Figma AI para maquetar rápido las pantallas, iterando sin perder horas en producción manual.",
      "Y usamos Claude y ChatGPT para todo el trabajo de oportunidad —problema, mapa de supuestos, hipótesis falsable.",
      "Un ejemplo rápido: al principio creíamos que el problema era el motor de recomendaciones. Iterando el mapa de supuestos con la IA, vimos que era pura intuición sin evidencia —el verdadero cuello de botella era la falta de señales tempranas.",
    ],
    highlight: [
      "Frase: IA aceleró el proceso, no reemplazó evidencia",
      "Insight del rumbo: señales tempranas, no motor roto",
      "Bloque corto · no alargar",
    ],
    avoid: [
      "No vender la demo de IA como validación de usuarios",
    ],
  },
  {
    id: 6,
    n: "07",
    title: "Prototipo ⭐",
    speaker: "Cristian",
    role: "Demo · 5:25→7:15 · ÉNFASIS",
    window: "5:25 → 7:15",
    onScreen: "3 swipes → perfil → home curada (WoZ) → play + métricas · Plan B",
    say: [
      "Les muestro la hipótesis hecha experimento —maqueta funcional en Figma, todavía en pulido.",
      "El problema, en una línea: el usuario nuevo llega sin historial, el sistema no tiene señales, y mientras aprende, el usuario se va.",
      "El outcome de este proto es acotado: comprobar si tres preferencias tempranas generan una portada más relevante y más reproducción, sin fricción —no estamos probando el algoritmo final, eso viene después.",
      "Es un Wizard of Oz longitudinal: el usuario cree que recibe recomendaciones automáticas, pero en esta fase las armamos manualmente con reglas simples. Elegimos este método porque hoy la incertidumbre es de deseabilidad y usabilidad, no de factibilidad técnica. Y corre en paralelo con un grupo control de portada genérica, para medir el efecto real de la señal.",
      "Primera pantalla: selección de tres géneros o títulos, con la lógica de interacción de Tinder —deslizar o tocar. Es la Ley de Jakob: el usuario ya conoce el patrón, así que no necesita aprenderlo, y eso genera affordance inmediato.",
      "Segunda pantalla: portada curada manualmente en esta fase —el truco del Wizard of Oz, probar la experiencia antes de construir el motor real.",
      "Este flujo produce las métricas exactas del experimento de Tami: finalización, tiempo de selección, reproducción válida, Watch Time y relevancia percibida —cada umbral es también un guardrail de refutación.",
      "Si el patrón funciona como esperamos, deberían ver alta finalización rápida y alta reproducción válida —eso es justo lo que Vale les muestra ahora.",
    ],
    highlight: [
      "⭐ Énfasis demo — mirar al jurado",
      "Ley de Jakob / Tinder-like",
      "Plan B: 1 vivo · 2 video · 3 capturas · D esta slide",
      "Pasar el arco limpio a Vale",
    ],
    avoid: [
      "No improvisar features fuera del tramo crítico",
      "No decir que ya corre el motor real",
    ],
  },
  {
    id: 7,
    n: "08",
    title: "Resultados",
    speaker: "Valeria",
    role: "Simulación · 7:15→8:25",
    window: "7:15 → 8:25",
    onScreen: "Banner simulación · 84% / 69% / +12% / 78% · Day-7 exploratorio 29→33",
    say: [
      "Estos son datos simulados para efectos del ejercicio, pero construidos de forma coherente con los criterios de éxito que definimos.",
      "El 84% de los usuarios completó la selección de gustos, en un promedio de 22 segundos —sobre la meta del 80% en menos de 30.",
      "El 69% hizo una reproducción válida durante su primera sesión, superando el umbral del 65%, con un tiempo mediano hasta esa primera reproducción de 2 minutos con 40 segundos.",
      "El Watch Time de la primera sesión subió 12% frente al grupo control, sobre la meta de 10%. Y el 78% calificó las recomendaciones con nota 4 o 5.",
      "Como métrica secundaria y cualitativa —no la pongo al mismo nivel que las anteriores, porque es intención declarada y no comportamiento observado— la intención de volver durante la semana aumentó 17%, por sobre el 15% esperado. Es una señal de que el usuario percibe valor, no una medición de retención real.",
      "Como señal exploratoria —y lo decimos con cuidado, porque con 30 a 50 usuarios no se puede afirmar esto estadísticamente— el Day-7 Retention de esta cohorte se movió de 29% a 33%. No es prueba, es una luz verde para seguir mirando.",
    ],
    highlight: [
      "Primera frase: “datos simulados”",
      "Separar primaria vs secundaria vs exploratoria",
      "Day-7 29→33 con cuidado · no victoria estadística",
    ],
    avoid: [
      "NUNCA presentar simulados como campo real",
      "No vender Day-7 como prueba de plataforma",
    ],
  },
  {
    id: 8,
    n: "09",
    title: "Aprendizajes ⭐",
    speaker: "Valeria",
    role: "Decisión · 8:25→9:45 · ÉNFASIS Y CIERRE",
    window: "8:25 → 9:45",
    onScreen: "3 aprendizajes · Confirma · 4 next steps · el pedido",
    say: [
      "¿Qué aprendimos? Que los usuarios sí están dispuestos a contarnos sus gustos en segundos, sin que eso se sienta como fricción. Que con solo tres señales tempranas se puede armar una portada que se percibe como relevante. Y que confirmamos algo clave: este es un problema de descubrimiento, no de catálogo ni de oferta de contenido.",
      "Antes de correr este experimento, definimos qué resultado contaba como confirma, refuta o inconcluso. Con estos números, la hipótesis cae en confirma: cumplimos los umbrales de activación y de relevancia percibida frente al grupo control, sin aumentar el abandono en el onboarding rediseñado.",
      "Por eso nuestra decisión es perseverar, con un ajuste: la próxima fase no puede seguir siendo curada a mano. El paso que sigue es conectar estas mismas señales de onboarding con el motor real, y complementarlas con las señales de sesión cero —dispositivo, hora, primeros clics— para que la personalización deje de depender de manual y empiece a aprender sola desde el primer minuto.",
      "Los próximos pasos que proponemos: primero, escalar esta prueba a una muestra representativa por región para poder hablar de Day-7 con solidez estadística. Segundo, trabajar con los equipos de Ingeniería y Data para que el motor real consuma estas señales tempranas, sin curación manual. Y tercero, probar este mismo flujo específicamente en perfiles nuevos dentro de cuentas familiares, porque ahí detectamos un riesgo distinto de mezcla de señales.",
      "Lo que les pedimos hoy es apoyo para pasar de un experimento de 30 a 50 usuarios a un piloto real con Ingeniería y Data detrás. Ya validamos que el usuario quiere esto. Ahora necesitamos construirlo de verdad.",
    ],
    highlight: [
      "⭐ Énfasis y cierre del arco de Vale",
      "Decisión predefinida · Confirma · perseverar con ajuste",
      "El ask: piloto real con Ingeniería y Data",
    ],
    avoid: [
      "No pedir “arreglar el algoritmo” sin el puente del piloto",
      "No reabrir todo el pitch en el ask",
    ],
  },
  {
    id: 9,
    n: "10",
    title: "Cierre",
    speaker: "Valeria",
    role: "Cierra · Q&A",
    window: "9:45 → fin",
    onScreen: "Gracias · equipo · Q&A",
    say: [
      "Gracias. ¿Preguntas?",
      "Ya validamos que el usuario quiere esto. Ahora necesitamos construirlo de verdad.",
    ],
    highlight: [
      "Equipo de pie o asiente",
      "Q&A: Erick cifras/fricciones · Tami hipótesis/experimento · Cris demo/IA · Vale decisión/ask",
    ],
    avoid: [
      "No reabrir el pitch completo en la respuesta",
      "No inventar cifras fuera de slide",
      "No presentar simulados como estudio real",
    ],
  },
];

window.WEBFLIX_SPEAKERS = {
  Erick: { name: "Erick Fuentealba", img: "../assets/Erick.png", color: "purple" },
  Tamara: { name: "Tamara Valdivia", img: "../assets/Tami.png", color: "amber" },
  Cristian: { name: "Cristian Pizarro", img: "../assets/Cris.png", color: "green" },
  Valeria: { name: "Valeria Nieto", img: "../assets/Vale.png", color: "cyan" },
};
