/* Notas del presentador · WebFlix Shark Tank v2
 * Frases cortas para leer en voz alta (sin meta-hablar del formato)
 * Erick → Tami → Cris → Vale
 */
window.WEBFLIX_NOTES = [
  {
    id: 0,
    n: "01",
    title: "Portada",
    speaker: "Erick",
    role: "Apertura",
    window: "Setup · saludo",
    onScreen: "Hook “Perdemos 1 de cada 3…” · 310M · 42%→29% · tesis Day-7",
    say: [
      "Hola a todos. Somos el equipo 5: Cris, Tami, Vale y yo.",
      "Trabajamos el caso de una plataforma global de streaming. Nosotros la llamamos WebFlix.",
      "El problema: quien se suscribe por primera vez no encuentra contenido relevante en la primera semana.",
      "Entra con ganas de ver algo. Se topa con un catálogo enorme que aún no sabe qué le gusta.",
      "Consume poco. Se frustra. Y se va antes del “primer momento de valor”.",
    ],
    highlight: [
      "Presentar al equipo en una frase",
      "Pausa tras el hook de cold start",
      "No leer todos los KPIs de portada",
    ],
    avoid: [
      "No prometer recuperar Day-7 hoy",
      "No alargar el saludo",
    ],
    glossary: [
      "Day-7",
      "cold-start",
      "primer-momento-valor",
      "outcome",
      "activacion",
      "relevancia",
    ],
  },
  {
    id: 1,
    n: "02",
    title: "Problema",
    speaker: "Erick",
    role: "Problema · 0:00→1:15",
    window: "0:00 → 1:15",
    onScreen: "42%→29% Day-7 · Watch Time / Sesiones / Churn · honestidad del experimento",
    say: [
      "¿A quién afecta? A todos los usuarios nuevos.",
      "La plataforma tiene 310 millones de suscriptores y cerca de 360 millones de usuarios activos al mes, contando perfiles.",
      "Ojo: un perfil nuevo en un plan familiar también cuenta, aunque la cuenta sea antigua.",
      "¿Por qué importa ahora? El Day-7 Retention cayó de 42% a 29%.",
      "Eso son trece puntos. Casi un 31% de caída relativa.",
      "No es un problema de catálogo. Es un problema de descubrimiento.",
      "Day-7 es el outcome de negocio que queremos recuperar.",
      "Pero seamos honestos desde ya: el experimento de hoy no prueba Day-7 en directo.",
      "Prueba los pasos previos: activación y relevancia en la primera sesión. Los que creemos que pueden moverlo.",
      "Guárdense esa distinción: outcome de negocio versus lo que medimos ahora.",
    ],
    highlight: [
      "310 M / ~360 M MAU = escala, no tamaño de muestra",
      "−13 pp · ≈31% de caída relativa",
      "Declarar honestidad: no probamos Day-7 directo",
    ],
    avoid: [
      "No decir “el algoritmo está roto”",
      "No vender Day-7 como resultado de este test",
    ],
    glossary: [
      "Day-7",
      "pp",
      "caida-relativa",
      "MAU",
      "activacion",
      "relevancia",
      "outcome",
      "supuesto",
    ],
  },
  {
    id: 2,
    n: "03",
    title: "Entendimiento",
    speaker: "Erick",
    role: "Tres fricciones · 1:15→2:15",
    window: "1:15 → 2:15",
    onScreen: "3 fricciones · insight “supuesto a validar” · cadena no virtuosa",
    say: [
      "Vemos tres fricciones concretas.",
      "Uno: el descubrimiento es lento. Hay que recorrer demasiadas categorías.",
      "Títulos, imágenes y descripciones no alcanzan para decidir rápido.",
      "Dos: el onboarding actual —elegir géneros al registrarse— es lento y pesado.",
      "No está pensado para segundos. Muchos lo abandonan o lo hacen a medias.",
      "No es que “sobra un paso”. Es que el paso que ya existe está mal diseñado.",
      "Tres —y este nos costó aislar—: el motor no está roto.",
      "Tarda en aprender porque llega con pocas señales.",
      "No falta oferta. Falta velocidad de personalización.",
      "Como equipo no asumimos que el motor era la causa.",
      "Lo tratamos como supuesto a validar, no como hecho. Eso cambió todo el enfoque.",
    ],
    highlight: [
      "Frase ancla: “el paso que ya existe está mal diseñado”",
      "Motor no roto → velocidad de personalización",
      "Supuesto a validar, no hecho",
    ],
    avoid: [
      "No culpar al catálogo como única causa",
      "No saltar a la solución sin las 3 fricciones",
    ],
    glossary: [
      "cold-start",
      "friccion",
      "onboarding",
      "supuesto",
      "sesion-cero",
    ],
  },
  {
    id: 3,
    n: "04",
    title: "Hipótesis",
    speaker: "Tamara",
    role: "Hipótesis · 2:15→3:10",
    window: "2:15 → 3:10",
    onScreen: "Rediseñar, no agregar · 3 elecciones · guardrail <30 s · H·C ★",
    say: [
      "Con eso en mente, priorizamos tres hipótesis en el tablero.",
      "H·A: patrones de usuarios similares.",
      "H·B: procesar más rápido las señales de sesión cero.",
      "Y H·C: la que probamos primero. Es la más rápida de validar y la de menor riesgo técnico.",
      "La hipótesis central: rediseñar —no agregar— la selección de gustos del onboarding.",
      "Dejarla en solo tres elecciones rápidas.",
      "Así el sistema gana señales suficientes para recomendar bien desde la primera sesión.",
      "Importante: no es un paso nuevo encima. Es el mismo paso, hecho liviano.",
      "Por eso menos de 30 segundos no es un “nice to have”. Es un guardrail.",
      "Si tarda más, la hipótesis se refuta ahí mismo. Sin mirar el resto de métricas.",
      "Éxito: menos tiempo hasta la primera reproducción.",
      "Y un +15% de usuarios que consumen contenido en su primera sesión.",
      "Apuesta simple. Barata de probar. No toca motor ni catálogo. Por eso va primero.",
    ],
    highlight: [
      "“Rediseñar, no agregar” es la frase ancla",
      "Guardrail <30 s = refutación inmediata",
      "Señalar H·C / onboarding liviano primero",
    ],
    avoid: [
      "No vender H·A / H·B como parte del test de hoy",
      "No tocar motor ni catálogo en el alcance",
    ],
    glossary: [
      "H-A",
      "H-B",
      "H-C",
      "guardrail",
      "<30s",
      "redisenar-no-agregar",
      "falsable",
      "onboarding",
    ],
  },
  {
    id: 4,
    n: "05",
    title: "Experimento ⭐",
    speaker: "Tamara",
    role: "Experimento · 3:10→4:50 · ÉNFASIS",
    window: "3:10 → 4:50",
    onScreen: "Control vs Experimental · umbrales · 30–50 · 7 días · 2 semanas",
    say: [
      "Para probarla sin armar el motor real, usamos un Wizard of Oz longitudinal.",
      "El usuario cree que recibe recomendaciones automáticas.",
      "En esta fase las armamos a mano, con perfiles de gustos predefinidos.",
      "Probamos la idea antes de invertir en ingeniería.",
      "Muestra: 30 a 50 usuarios nuevos. Perfil recién creado. Incluye perfiles nuevos en cuentas familiares.",
      "Les pedimos tres géneros o títulos en el onboarding rediseñado.",
      "Con eso los asignamos a un perfil predefinido y les mostramos una home curada.",
      "En paralelo va el control: portada genérica, sin selección de preferencias.",
      "Así la diferencia se la atribuimos a la señal, no al azar.",
      "Medimos la primera sesión de ambos grupos. Y los seguimos siete días con analítica y un diario breve.",
      "Total: dos semanas entre recluta, ejecución y análisis. Siete días de seguimiento por persona.",
      "Criterios de éxito, uno por uno:",
      "Al menos 80% completa la selección en menos de 30 segundos.",
      "Al menos 65% hace un play válido en la primera sesión.",
      "Tiempo mediano a esa primera play: menos de 3 minutos.",
      "Watch Time de sesión 1: +10% vs control.",
      "Al menos 75% califica las recomendaciones con 4 o 5.",
      "Intención de volver en la semana: +15%.",
      "Si no se cumple —o si sube el abandono— la hipótesis queda refutada. Volvemos al tablero.",
    ],
    highlight: [
      "⭐ Énfasis del bloque de Tami",
      "Control vs “la apuesta” experimental",
      "WoZ = techo de valor, no promesa del motor",
      "Listar umbrales con calma; no correr",
    ],
    avoid: [
      "No hablar de significancia a escala WebFlix",
      "No confundir curación manual con producto final",
    ],
    glossary: [
      "WoZ",
      "longitudinal",
      "control",
      "experimental",
      "guardrail",
      "<30s",
      "play-valido",
      "Watch-Time",
      "umbral",
      "n-direccional",
      "refutacion",
    ],
  },
  {
    id: 5,
    n: "06",
    title: "Herramientas",
    speaker: "Cristian",
    role: "IA copiloto · 4:50→5:25",
    window: "4:50 → 5:25",
    onScreen: "Figma AI · Claude + ChatGPT · ejemplo que cambió el rumbo",
    say: [
      "Con la hipótesis de Tami ya fijada, les cuento cómo llegamos ahí.",
      "Figma AI para maquetar pantallas rápido. Sin horas de producción manual.",
      "Claude y ChatGPT para el trabajo de oportunidad: problema, mapa de supuestos e hipótesis falsable.",
      "Un ejemplo: al inicio creíamos que el problema era el motor.",
      "Al iterar el mapa de supuestos vimos que era intuición sin evidencia.",
      "El cuello real era la falta de señales tempranas.",
    ],
    highlight: [
      "Frase: IA aceleró el proceso, no reemplazó evidencia",
      "Insight del rumbo: señales tempranas, no motor roto",
      "Bloque corto · no alargar",
    ],
    avoid: [
      "No vender la demo de IA como validación de usuarios",
    ],
    glossary: [
      "copiloto",
      "supuesto",
      "cold-start",
      "falsable",
    ],
  },
  {
    id: 6,
    n: "07",
    title: "Prototipo ⭐",
    speaker: "Cristian",
    role: "Demo · 5:25→7:15 · ÉNFASIS",
    window: "5:25 → 7:15",
    onScreen: "3 swipes → perfil → home curada (WoZ) → play + métricas · Plan B",
    say: [
      "Les muestro la hipótesis hecha experimento. Maqueta en Figma, aún en pulido.",
      "El problema en una línea: llega sin historial, el sistema no tiene señales, y mientras aprende… el usuario se va.",
      "El outcome de este proto es acotado.",
      "¿Tres preferencias tempranas dan una portada más relevante y más reproducción, sin fricción?",
      "No estamos probando el algoritmo final. Eso viene después.",
      "Es Wizard of Oz: el usuario cree que es automático; nosotros curamos a mano con reglas simples.",
      "Lo elegimos porque la incertidumbre hoy es de deseabilidad y usabilidad, no de factibilidad técnica.",
      "Y corre en paralelo con un control de portada genérica, para medir el efecto de la señal.",
      "Pantalla 1: tres géneros o títulos, con gesto tipo Tinder —deslizar o tocar.",
      "Ley de Jakob: el patrón ya se conoce, no hay que enseñarlo. Affordance inmediato.",
      "Pantalla 2: home curada a mano. El truco del Wizard of Oz: probar la experiencia antes del motor real.",
      "Este flujo entrega las mismas métricas del experimento de Tami: finalización, tiempo, play válido, Watch Time y relevancia.",
      "Cada umbral es también un guardrail de refutación.",
      "Si el patrón funciona, deberían ver alta finalización rápida y alta reproducción válida. Eso es lo que Vale muestra ahora.",
    ],
    highlight: [
      "⭐ Énfasis demo — mirar al jurado",
      "Ley de Jakob / Tinder-like",
      "Plan B demo: 1 vivo · 2 video · 3 capturas",
      "Cerrar el puente y ceder a Vale",
    ],
    avoid: [
      "No improvisar features fuera del tramo crítico",
      "No decir que ya corre el motor real",
    ],
    glossary: [
      "WoZ",
      "tramo-critico",
      "Ley-Jakob",
      "affordance",
      "guardrail",
      "<30s",
      "play-valido",
      "Watch-Time",
      "control",
    ],
  },
  {
    id: 7,
    n: "08",
    title: "Resultados",
    speaker: "Valeria",
    role: "Simulación · 7:15→8:25",
    window: "7:15 → 8:25",
    onScreen: "Banner simulación · 84% / 69% / +12% / 78% · Day-7 exploratorio 29→33",
    say: [
      "Estos son datos simulados para el ejercicio.",
      "Están armados de forma coherente con los criterios de éxito que definimos.",
      "84% completó la selección de gustos. Promedio: 22 segundos. Meta: 80% en menos de 30.",
      "69% hizo un play válido en la primera sesión. Meta: 65%.",
      "Tiempo mediano a esa primera play: 2 minutos 40 segundos.",
      "Watch Time de sesión 1: +12% vs control. Meta: +10%.",
      "78% calificó las recomendaciones con 4 o 5.",
      "Métrica secundaria —cualitativa—: intención de volver en la semana +17%. Meta: +15%.",
      "Ojo: es lo que el usuario declara, no retención observada. No la pongo al mismo nivel que las anteriores.",
      "Señal exploratoria, con cuidado: Day-7 de esta cohorte de 29% a 33%.",
      "Con 30 a 50 usuarios no se puede afirmar esto estadísticamente.",
      "No es prueba. Es una luz verde para seguir mirando.",
    ],
    highlight: [
      "Primera frase: “datos simulados”",
      "Separar primaria vs secundaria vs exploratoria",
      "Day-7 29→33 con cuidado · no victoria estadística",
    ],
    avoid: [
      "NUNCA presentar simulados como campo real",
      "No vender Day-7 como prueba de plataforma",
    ],
    glossary: [
      "simulacion",
      "play-valido",
      "Watch-Time",
      "guardrail",
      "intencion-declarada",
      "exploratoria",
      "Day-7",
      "n-direccional",
    ],
  },
  {
    id: 8,
    n: "09",
    title: "Aprendizajes ⭐",
    speaker: "Valeria",
    role: "Decisión · 8:25→9:45 · ÉNFASIS Y CIERRE",
    window: "8:25 → 9:45",
    onScreen: "3 aprendizajes · Confirma · 4 next steps · el pedido",
    say: [
      "¿Qué aprendimos?",
      "Los usuarios sí cuentan sus gustos en segundos, sin que se sienta como fricción.",
      "Con tres señales tempranas se puede armar una portada que se percibe como relevante.",
      "Y lo clave: es un problema de descubrimiento. No de catálogo ni de falta de oferta.",
      "Antes de correr el experimento, definimos qué contaba como confirma, refuta o inconcluso.",
      "Con estos números, cae en confirma.",
      "Cumplimos activación y relevancia vs control. Sin subir el abandono en el onboarding rediseñado.",
      "Por eso la decisión es perseverar… con un ajuste.",
      "La próxima fase no puede seguir curada a mano.",
      "Hay que conectar estas señales de onboarding con el motor real.",
      "Y sumar señales de sesión cero: dispositivo, hora, primeros clics.",
      "Así la personalización deja de ser manual y aprende sola desde el primer minuto.",
      "Próximos pasos.",
      "Uno: escalar a una muestra representativa por región, para hablar de Day-7 con solidez.",
      "Dos: Ingeniería y Data — que el motor real consuma estas señales, sin curación manual.",
      "Tres: probar el mismo flujo en perfiles nuevos de cuentas familiares. Ahí hay riesgo de mezcla de señales.",
      "Lo que pedimos hoy: apoyo para pasar de 30–50 usuarios a un piloto real con Ingeniería y Data.",
      "Ya validamos que el usuario quiere esto. Ahora hay que construirlo de verdad.",
    ],
    highlight: [
      "⭐ Énfasis y cierre del arco de Vale",
      "Decisión predefinida · Confirma · perseverar con ajuste",
      "El ask: piloto real con Ingeniería y Data",
    ],
    avoid: [
      "No pedir “arreglar el algoritmo” sin el puente del piloto",
      "No reabrir todo el argumento en el pedido",
    ],
    glossary: [
      "confirma",
      "perseverar",
      "piloto",
      "sesion-cero",
      "mezcla-senales",
      "guardrail",
      "refutacion",
    ],
  },
  {
    id: 9,
    n: "10",
    title: "Cierre",
    speaker: "Valeria",
    role: "Cierra · Q&A",
    window: "9:45 → fin",
    onScreen: "Gracias · equipo · Q&A · pistas",
    say: [
      "Gracias. ¿Preguntas?",
      "Ya validamos que el usuario quiere esto. Ahora necesitamos construirlo de verdad.",
    ],
    highlight: [
      "Equipo de pie o asiente",
      "Abrir panel Q&A (tecla Q) con pistas",
      "Mapa: Erick cifras · Tami hip/exp · Cris demo · Vale decisión",
      "Si atacan el momento del onboarding: Plan B · Exp. 2 (selector en D1–D7 a no-players)",
    ],
    avoid: [
      "No recontar todo el caso en cada respuesta",
      "No inventar cifras que no estén en pantalla",
      "No presentar simulados como estudio real",
      "No defender el Plan B como claim de hoy — es contingencia",
    ],
    glossary: [
      "piloto",
      "Plan-B-Exp2",
      "simulacion",
      "Day-7",
      "confirma",
      "guardrail",
      "H-C",
    ],
  },
];

window.WEBFLIX_SPEAKERS = {
  Erick: { name: "Erick Fuentealba", img: "../assets/Erick.png", color: "purple" },
  Tamara: { name: "Tamara Valdivia", img: "../assets/Tami.png", color: "amber" },
  Cristian: { name: "Cristian Pizarro", img: "../assets/Cris.png", color: "green" },
  Valeria: { name: "Valeria Nieto", img: "../assets/Vale.png", color: "cyan" },
};
